<a href="https://colab.research.google.com/github/yeongminChae/numpy_Start/blob/main/Numpy6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

## Section 5. N차원의 배열의 형태 변경

1.   5-1. 배열의 형태 변경1 : reshape()



In [ ]:
arr = np.arange(12)
print(arr, arr.ndim)

arr = arr.reshape((3,4))
print(arr, arr.ndim)

arr = arr.reshape((2,3,2))
print(arr, arr.ndim)

arr = arr.reshape(3,-1) #-1 입력시 자동으로 4입력 
print(arr)

arr = arr.reshape(3,2,-1) # -1 대신 자동으로 2입력
print(arr)


[ 0  1  2  3  4  5  6  7  8  9 10 11] 1
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 2
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]] 3
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]]




2.   5-1. 배열의 형태 변경2 :resize,ravel



In [ ]:
arr=np.arange(12)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [ ]:
arr.resize(3,4)
print(arr)
arr=arr.ravel() #1차원으로 변경
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]




3.   5-3.배열의 형태 변경3 : expand_dims(),squeeze()



In [ ]:
#expand_dims()
arr = np.array([1,2])
print(arr, arr.shape)
arr = np.expand_dims(arr, axis=0) # row 값 기준
print(arr, arr.shape)

[1 2] (2,)
[[1 2]] (1, 2)


In [ ]:
arr = np.expand_dims(arr, axis=1) # column 값 기준
print(arr, arr.shape)

[[[1]]

 [[2]]] (2, 1, 1)


In [ ]:
# squeeze() # 배열의 축 하나 제거, 차원 축소 
arr=np.array([[1,2]])
print(arr, arr.shape, arr.ndim)
arr = np.squeeze(arr, axis=0) # x축제거
print(arr, arr.shape, arr.ndim)
arr=np.array([[[1],
               [2],
               [3]]])
print(arr,arr.shape,arr.ndim)
arr=np.squeeze(arr, axis=0)
print(arr,arr.shape, arr.ndim)

[[1 2]] (1, 2) 2
[1 2] (2,) 1
[[[1]
  [2]
  [3]]] (1, 3, 1) 3
[[1]
 [2]
 [3]] (3, 1) 2


In [ ]:
arr=np.array([[[1,2,3]]])
print(arr,arr.shape, arr.ndim)
arr=np.squeeze(arr,axis=1) # y축제거
print(arr,arr.shape, arr.ndim)
#axis 입력하지 않으면 행령,텐서든 모든지 1차원으로 축소

[[[1 2 3]]] (1, 1, 3) 3
[[1 2 3]] (1, 3) 2




5.   5-5. 전치행렬 (transpose)



In [5]:
# 정반행렬 : 같은 개수의 행과 열을 가진 행렬

arr = np.array([[1,2],
                [3,4]])
print(arr.T)
arr = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])
print(arr.T)

[[1 3]
 [2 4]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [8]:
arr = np.array([[1,2],
                [3,4],
                [5,6]])
print(arr.T)
arr2 = np.full((3,2),2)
print(arr.dot(arr2.T))

[[1 3 5]
 [2 4 6]]
[[ 6  6  6]
 [14 14 14]
 [22 22 22]]
