<a href="https://colab.research.google.com/github/yeongminChae/numpy_Start/blob/main/numpy1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [5]:
#1차원 배열
arr = np.array([1,2,3] )
print(arr)
#2차원 배열
arr2 = np.array([[1,2,3],
               [4,5,6]])
print(arr2)

[1 2 3]
[[1 2 3]
 [4 5 6]]


In [9]:
tpl = (4,5,6)
arr = np.array(tpl)
print(arr)
lst =[1,2,3]
arr2 = np.array(lst)
print(arr2)
lst2=[[1,2,3],[4,5,6]]
arr3=np.array(lst2)
print(arr3)

[4 5 6]
[1 2 3]
[[1 2 3]
 [4 5 6]]


In [13]:
#shape
arr1 = np.array([1,2,3])
arr2= np.array([[1,2,3],[4,5,6]])
print(arr1.shape,arr2.shape)
#(2, 3) = 2행 3열 2차원 array

#ndim n 차원 
print(arr1.ndim, arr2.ndim)

# size 원소 개수
print(arr1.size, arr2.size)

(3,) (2, 3)
1 2
3 6
