<a href="https://colab.research.google.com/github/yeongminChae/numpy_Start/blob/main/Numpy7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

Section 6. N차원 배열의 병합

1.   6-1. 배열에 원소 추가 및 삭제



In [4]:
# python list 
arr = [1,2,3,4,5,6,7,8]
arr.insert(2,50)
print(arr)

# 1차원 배열
arr = np.arange(1,9)
arr = np.insert(arr,2,50)
print(arr)

[1, 2, 50, 3, 4, 5, 6, 7, 8]
[ 1  2 50  3  4  5  6  7  8]


In [9]:
# 2차원 배열
arr = np.arange(1,13).reshape(3,4)
arr = np.insert(arr,2,50,axis=0)
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [50 50 50 50]
 [ 9 10 11 12]]


In [8]:
arr = np.arange(1,13).reshape(3,4)
arr = np.insert(arr,2,50,axis=1) #axis 값을 주지 않으면 1차원 배열을 변경
print(arr)

[[ 1  2 50  3  4]
 [ 5  6 50  7  8]
 [ 9 10 50 11 12]]


In [13]:
# delete()
arr = np.arange(1,13).reshape(3,4)
print(arr)
arr = np.delete(arr,2,axis=0)
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[1 2 3 4]
 [5 6 7 8]]


In [14]:
arr = np.arange(1,13).reshape(3,4)
print(arr)
arr = np.delete(arr,2,axis=1) #axis 값을 주지 않으면 1차원 배열을 삭제
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  4]
 [ 5  6  8]
 [ 9 10 12]]




2.   6-2. 배열 간의 병합



In [16]:
# append()
arr1 = np.arange(1,13).reshape(3,4)
arr2 = np.arange(13,25).reshape(3,4)

print(arr1)
print(arr2,end='\n\n')

# axis=0
arr3 = np.append(arr1,arr2,axis=0)#axis 값을 주지 않으면 1차원 배열을 병합
print(arr3,end='\n\n')

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]



In [17]:
# axis=1
arr3 = np.append(arr1,arr2,axis=1)
print(arr3,end='\n\n')

[[ 1  2  3  4 13 14 15 16]
 [ 5  6  7  8 17 18 19 20]
 [ 9 10 11 12 21 22 23 24]]



In [21]:
# vstack(), hstack()
arr1 = np.arange(1,7).reshape(2,3)
arr2 = np.arange(7,13).reshape(2,3)
arr3 = np.vstack((arr1,arr2))
print(arr3)
arr3 = np.hstack((arr1,arr2))
print(arr3)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [23]:
# concatenate()
arr1 = np.arange(1,7).reshape(2,3)
arr2 = np.arange(7,13).reshape(2,3)
arr3 = np.concatenate([arr1,arr2], axis=0)
print(arr3)
arr3 = np.concatenate([arr1,arr2], axis=1)
print(arr3)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]




3.   6-3. 배열 분할



In [29]:
# 2차원 배열
arr = np.arange(1,13).reshape(3,4)
print(arr)

#vsplit() => axis=0
arr_vsplit=np.vsplit(arr,3) # 짝수개로 분할 시 에러발생
print(arr_vsplit)

#hsplit() => axis=1
arr_hsplit=np.hsplit(arr,2) # 짝수개로 분할 시 에러발생
print(arr_hsplit)



[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]]), array([[ 9, 10, 11, 12]])]
[array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]]), array([[ 3,  4],
       [ 7,  8],
       [11, 12]])]


In [31]:
# 3 차원 배열
arr = np.random.randint(0,10,(4,6,8)) # -> 0~10 까지 숫자를 8행 6열 에 행렬을 4세트 생성
print(arr)

[[[4 4 8 4 3 1 6 4]
  [6 3 9 1 4 1 4 9]
  [0 2 6 7 8 4 3 8]
  [4 0 6 5 9 5 9 5]
  [7 9 8 5 7 0 3 2]
  [7 3 7 7 6 3 8 6]]

 [[5 9 6 7 5 4 0 8]
  [1 2 6 7 9 8 4 7]
  [8 9 5 3 7 7 6 9]
  [3 5 5 4 3 0 5 8]
  [9 1 7 9 6 7 6 4]
  [5 6 3 1 9 1 2 8]]

 [[5 9 0 4 7 8 5 1]
  [5 5 2 2 3 8 9 2]
  [7 9 2 1 9 9 4 1]
  [6 9 5 5 8 6 7 5]
  [1 2 6 1 5 0 3 0]
  [0 9 4 8 7 8 1 0]]

 [[2 6 2 4 2 7 2 4]
  [0 4 9 9 5 9 2 2]
  [2 5 5 0 9 7 5 6]
  [3 0 3 2 7 0 6 0]
  [5 9 2 4 8 8 9 6]
  [7 6 2 6 5 5 3 4]]]


In [33]:
arr_vsplit = np.vsplit(arr,2)
print(arr_vsplit)

[array([[[4, 4, 8, 4, 3, 1, 6, 4],
        [6, 3, 9, 1, 4, 1, 4, 9],
        [0, 2, 6, 7, 8, 4, 3, 8],
        [4, 0, 6, 5, 9, 5, 9, 5],
        [7, 9, 8, 5, 7, 0, 3, 2],
        [7, 3, 7, 7, 6, 3, 8, 6]],

       [[5, 9, 6, 7, 5, 4, 0, 8],
        [1, 2, 6, 7, 9, 8, 4, 7],
        [8, 9, 5, 3, 7, 7, 6, 9],
        [3, 5, 5, 4, 3, 0, 5, 8],
        [9, 1, 7, 9, 6, 7, 6, 4],
        [5, 6, 3, 1, 9, 1, 2, 8]]]), array([[[5, 9, 0, 4, 7, 8, 5, 1],
        [5, 5, 2, 2, 3, 8, 9, 2],
        [7, 9, 2, 1, 9, 9, 4, 1],
        [6, 9, 5, 5, 8, 6, 7, 5],
        [1, 2, 6, 1, 5, 0, 3, 0],
        [0, 9, 4, 8, 7, 8, 1, 0]],

       [[2, 6, 2, 4, 2, 7, 2, 4],
        [0, 4, 9, 9, 5, 9, 2, 2],
        [2, 5, 5, 0, 9, 7, 5, 6],
        [3, 0, 3, 2, 7, 0, 6, 0],
        [5, 9, 2, 4, 8, 8, 9, 6],
        [7, 6, 2, 6, 5, 5, 3, 4]]])]


In [34]:
arr_hsplit = np.hsplit(arr,2)
print(arr_hsplit)

[array([[[4, 4, 8, 4, 3, 1, 6, 4],
        [6, 3, 9, 1, 4, 1, 4, 9],
        [0, 2, 6, 7, 8, 4, 3, 8]],

       [[5, 9, 6, 7, 5, 4, 0, 8],
        [1, 2, 6, 7, 9, 8, 4, 7],
        [8, 9, 5, 3, 7, 7, 6, 9]],

       [[5, 9, 0, 4, 7, 8, 5, 1],
        [5, 5, 2, 2, 3, 8, 9, 2],
        [7, 9, 2, 1, 9, 9, 4, 1]],

       [[2, 6, 2, 4, 2, 7, 2, 4],
        [0, 4, 9, 9, 5, 9, 2, 2],
        [2, 5, 5, 0, 9, 7, 5, 6]]]), array([[[4, 0, 6, 5, 9, 5, 9, 5],
        [7, 9, 8, 5, 7, 0, 3, 2],
        [7, 3, 7, 7, 6, 3, 8, 6]],

       [[3, 5, 5, 4, 3, 0, 5, 8],
        [9, 1, 7, 9, 6, 7, 6, 4],
        [5, 6, 3, 1, 9, 1, 2, 8]],

       [[6, 9, 5, 5, 8, 6, 7, 5],
        [1, 2, 6, 1, 5, 0, 3, 0],
        [0, 9, 4, 8, 7, 8, 1, 0]],

       [[3, 0, 3, 2, 7, 0, 6, 0],
        [5, 9, 2, 4, 8, 8, 9, 6],
        [7, 6, 2, 6, 5, 5, 3, 4]]])]
