<a href="https://colab.research.google.com/github/yeongminChae/numpy_Start/blob/main/Numpy5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

## Section 4. N차원 배열 정렬

1.   4-1. 1차원 배열의 정렬



In [ ]:
arr = np.random.randint(10,size=10)
print(np.sort(arr)) # 오름차순 정리
print(np.sort(arr)[::-1]) # 내림차순 정리

In [ ]:
arr.sort()
print(arr) #원본 배열도 차순 정리 유지


2.   4-2. 2차원 배열의 정렬



In [10]:
arr=np.random.randint(15,size=(3,4))
print(arr)

[[ 2  8 11 11]
 [13  2 13 11]
 [14  9 14 11]]


In [ ]:
print(np.sort(arr)) # 오름차순
print(np.sort(arr, axis=0)) 
print(np.sort(arr, axis=None)) # 2차원 배열을 1차원 배열로 정렬

In [ ]:
# argsort()
print(np.sort(arr, axis=1))
print(np.argsort(arr, axis=1)) # 원래 배열에서의 원소의 인덱스 위치

In [ ]:
print(np.sort(arr, axis=0))
print(np.argsort(arr, axis=0)) # 원래 배열에서의 원소의 인덱스 위치