<a href="https://colab.research.google.com/github/yeongminChae/numpy_Start/blob/main/Numpy3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

## section 2. N차원 배열 인덱싱

1.   2-1 배열의 index 접근하기



In [7]:
#1차원 배열
arr = np.array([0,1,2,3,4,5,6,7,8,9])
arr1 = np.arange(10)
print(arr)
print(arr1)

print(arr[3])
print(arr[-1])

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
3
9


In [13]:
#2차원 배열
arr = np.array([[1,2,3,4],
                [5,6,7,8],
                [9,10,11,12]])
print(arr,arr.shape,arr.ndim)
print(arr[0][3])
print(arr[0,3])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] (3, 4) 2
4
4


In [15]:
arr = np.array([0,1,2,3,4,5,6,7,8,9])
print(arr[3:8])
print(arr[:-1])

[3 4 5 6 7]
[0 1 2 3 4 5 6 7 8]


In [17]:
arr = np.array([[1,2,3,4],
                [5,6,7,8],
                [9,10,11,12]])
print(arr[0,:])
print(arr[:,1])

[1 2 3 4]
[ 2  6 10]


In [19]:
print(arr[:3,:])
print(arr[:2,2:])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[3 4]
 [7 8]]



2.   2-2 배열의 fancy 인덱싱



In [21]:
# 1차원 배열
arr = np.array([5,10,15,20,25,30])
print(arr[[0,2,4]])

[ 5 15 25]


In [23]:
#2차원 배열
arr = np.array([[5,10,15,20],   #0행
                [25,30,35,40],  #1행
                [45,50,55,60]]) #2행
print(arr[[0,2],2:])
print(arr[1:,[2,3]])
#arr([행],[열] )

[[15 20]
 [55 60]]
[[35 40]
 [55 60]]





.   2-3 배열의 Boolean 인덱싱



In [26]:
arr = np.array([1,2,3,4])
print(arr[[True,False,True,True]])

arr = np.array([[1,2,3,4],
                [5,6,7,8]])
print(arr[[True,False],True])

[1 3 4]
[[1 2 3 4]]


In [28]:
arr = np.array([[1,2,3,4],
                [5,6,7,8]])
print(arr[arr>4])
print(arr[arr<=2])

[5 6 7 8]
[1 2]
