<a href="https://colab.research.google.com/github/yeongminChae/numpy_Start/blob/main/Numpy4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

Section 3. N차원 배열 연산법

1.   3-1. 배열의 연산 : 사칙연산/제곱/제곱근/몫/나머지



In [ ]:
arr1 = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])
arr2 = np.array([[2,2,2],
                 [2,2,2],
                 [2,2,2]])
print(arr1)
print(arr2)

In [ ]:
# 덧셈
print(arr1 + arr2)
print(np.add(arr1,arr2))
# 뺄셈 
print(arr1 - arr2)
print(np.subtract(arr1,arr2))
#곱셈
print(arr1 * arr2)
print(np.multiply(arr1,arr2))
#나눗셈
print(arr1 / arr2)
print(np.divide(arr1,arr2))

In [ ]:
#제곱
arr1 = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])
arr2 = np.array([[2,2,2],
                 [2,2,2],
                 [2,2,2]])
print(arr1 ** 2)
print(np.square(arr1))
#제곱근
print(np.sqrt(arr1))
#몫
print(arr1 // 2)
#나머지
print(arr1 % 2)



2.   3-2. 배열의 연산2 : 내적(dot product)/절댓값/올림/내림/반올림/버림



In [22]:
# 1차원 행렬
arr1 = np.array([2,3,4])
arr2 = np.array([1,2,3])
print(np.dot(arr1,arr2))
# (2*1 + 3*2 + 4*3)

20


In [25]:
# 2차원 행렬
# [[a,b] [e,f]    =>  [[ae + bg , af + bh]
#  [c,d] [g,h]]   =>   [ce + dg , cf + dh]]

arr1 = np.array([[1,2],
                 [4,5]])
arr2 = np.array([[1,2],
                 [0,3]])
print(np.dot(arr1,arr2))


[[ 1  8]
 [ 4 23]]


In [31]:
# 절댓값
arr1 = np.array([[1,-2],
                 [-4,5]])
print(np.abs(arr1))
# 올림 , 내림 , 반올림 , 버림
arr1 = np.array([[1.932,-2.339], 
                 [-4.145,5.206]])
print(np.ceil(arr1)) #올림
print(np.floor(arr1)) #내림
print(np.round(arr1)) #반올림
print(np.trunc(arr1)) #버림

[[1 2]
 [4 5]]
[[ 2. -2.]
 [-4.  6.]]
[[ 1. -3.]
 [-5.  5.]]
[[ 2. -2.]
 [-4.  5.]]
[[ 1. -2.]
 [-4.  5.]]




3.   3-3. 배열의 연산3 : min/max/sum/mean/std/cumsum/median



In [ ]:
arr = np.array([[1,2,3],
                [0,1,4]])

#min
print(np.min(arr))
print(arr.min())
print(arr.min(axis=0)) #세로
print(arr.min(axis=1)) #가로

In [ ]:
#max
print(np.max(arr))
print(arr.max(axis=0))
print(arr.max(axis=1))

In [ ]:
#sum
print(np.sum(arr))
print(arr.sum(axis=0))
print(arr.sum(axis=1))

In [ ]:
#mean(평균)
print(np.mean(arr))
print(arr.mean(axis=0))
print(arr.mean(axis=1))

In [ ]:
#std(표준편차)
print(np.std(arr))
print(arr.std(axis=0))
print(arr.std(axis=1))

In [ ]:
#cumsum (누적핪)
print(np.cumsum(arr))
print(arr.cumsum())
print(arr.cumsum(axis=0))
print(arr.cumsum(axis=1))

In [50]:
#median (중간값)
print(np.median(arr))
print(np.median(arr,axis=0))
print(np.median(arr,axis=1))

1.5
[0.5 1.5 3.5]
[2. 1.]




4.   3-4. 배열의 연산4 : 비교 연산 / 삼각 함수





In [ ]:
# 비교 연산
arr1 = np.array([[1,2,3],
                 [4,5,6]])
arr2 = np.array([[1,0,3],
                 [4,-2,9]])
print(arr1 == arr2) # 동일하면 True 다르면 False
print(arr1 >= arr2) # 크면 True 작으면 False
print(np.array_equal(arr1,arr2)) # 원소가다르다면 False

In [ ]:
# 삼각함수
arr = np.array([[1,2,3],
                [4,5,6]])
# sin
print(np.sin(arr))
# cos
print(np.cos(arr))
# tan
print(np.tan(arr))
# pi
print(np.pi)



5.   3-5. 브로드캐스팅(brocasting)



In [ ]:
arr1 = np.array([[0,0,0],
                 [1,1,1],
                 [2,2,2]])
arr2 = np.array([[5,6,7]])
print(arr1 + arr2)      

arr1 = np.array([[1,1,1]])
arr2 = np.array([[1]])
print(arr1 + arr2)


6.   3-6. 벡터 연산의 장점



In [61]:
import time

In [63]:
arr1 = np.arange(9999999)
arr2 = np.arange(9999999)
before = time.time()
sum = np.dot(arr1,arr2)
after = time.time()
print(f'{sum} , {after-before}초')

1291790006583070911 , 0.016984939575195312초


In [ ]:
# for 문 사용시에는 연산에 1분이 넘는 시간이 소요되지만, 벡터 내적을 사용하여 연산하면 훨씬 시간을 단축 시킬 수 있다.